/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const GameMode = IDL.Variant({
  'endless' : IDL.Null,
  'strategy' : IDL.Null,
  'advancedStrategy' : IDL.Null,
  'powerBoost' : IDL.Null,
  'timeAttack' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'lastLoginTime' : Time,
  'powerUps' : IDL.Nat,
  'name' : IDL.Text,
  'preferredGameMode' : GameMode,
  'dailyLoginStreak' : IDL.Nat,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const MissionReward = IDL.Variant({
  'powerUps' : IDL.Nat,
  'comboBoost' : IDL.Float64,
  'points' : IDL.Nat,
});
export const MissionType = IDL.Variant({
  'clearTotalLines' : IDL.Nat,
  'clearLines' : IDL.Nat,
  'completeGames' : IDL.Nat,
  'usePowerUps' : IDL.Nat,
  'comboMultiplier' : IDL.Nat,
  'scorePoints' : IDL.Nat,
  'triggerChains' : IDL.Nat,
});
export const DailyMission = IDL.Record({
  'reward' : MissionReward,
  'missionType' : MissionType,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'claimed' : IDL.Bool,
  'progress' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyMissions' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(DailyMission))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDailyMissions' : IDL.Func([IDL.Vec(DailyMission)], [], []),
  'selectGameMode' : IDL.Func([GameMode], [], []),
  'updateAvatar' : IDL.Func([ExternalBlob], [], []),
  'updateDailyLoginStreak' : IDL.Func([IDL.Nat], [], []),
  'updateLastLoginTime' : IDL.Func([Time], [], []),
  'updatePowerUps' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const GameMode = IDL.Variant({
    'endless' : IDL.Null,
    'strategy' : IDL.Null,
    'advancedStrategy' : IDL.Null,
    'powerBoost' : IDL.Null,
    'timeAttack' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'lastLoginTime' : Time,
    'powerUps' : IDL.Nat,
    'name' : IDL.Text,
    'preferredGameMode' : GameMode,
    'dailyLoginStreak' : IDL.Nat,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const MissionReward = IDL.Variant({
    'powerUps' : IDL.Nat,
    'comboBoost' : IDL.Float64,
    'points' : IDL.Nat,
  });
  const MissionType = IDL.Variant({
    'clearTotalLines' : IDL.Nat,
    'clearLines' : IDL.Nat,
    'completeGames' : IDL.Nat,
    'usePowerUps' : IDL.Nat,
    'comboMultiplier' : IDL.Nat,
    'scorePoints' : IDL.Nat,
    'triggerChains' : IDL.Nat,
  });
  const DailyMission = IDL.Record({
    'reward' : MissionReward,
    'missionType' : MissionType,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'claimed' : IDL.Bool,
    'progress' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyMissions' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(DailyMission))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDailyMissions' : IDL.Func([IDL.Vec(DailyMission)], [], []),
    'selectGameMode' : IDL.Func([GameMode], [], []),
    'updateAvatar' : IDL.Func([ExternalBlob], [], []),
    'updateDailyLoginStreak' : IDL.Func([IDL.Nat], [], []),
    'updateLastLoginTime' : IDL.Func([Time], [], []),
    'updatePowerUps' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };