/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type MissionReward = {
    __kind__: "powerUps";
    powerUps: bigint;
} | {
    __kind__: "comboBoost";
    comboBoost: number;
} | {
    __kind__: "points";
    points: bigint;
};
export type MissionType = {
    __kind__: "clearTotalLines";
    clearTotalLines: bigint;
} | {
    __kind__: "clearLines";
    clearLines: bigint;
} | {
    __kind__: "completeGames";
    completeGames: bigint;
} | {
    __kind__: "usePowerUps";
    usePowerUps: bigint;
} | {
    __kind__: "comboMultiplier";
    comboMultiplier: bigint;
} | {
    __kind__: "scorePoints";
    scorePoints: bigint;
} | {
    __kind__: "triggerChains";
    triggerChains: bigint;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DailyMission {
    reward: MissionReward;
    missionType: MissionType;
    completed: boolean;
    description: string;
    claimed: boolean;
    progress: bigint;
}
export interface UserProfile {
    lastLoginTime: Time;
    powerUps: bigint;
    name: string;
    preferredGameMode: GameMode;
    dailyLoginStreak: bigint;
    avatar?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum GameMode {
    endless = "endless",
    strategy = "strategy",
    advancedStrategy = "advancedStrategy",
    powerBoost = "powerBoost",
    timeAttack = "timeAttack"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyMissions(): Promise<Array<DailyMission> | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDailyMissions(missions: Array<DailyMission>): Promise<void>;
    selectGameMode(mode: GameMode): Promise<void>;
    updateAvatar(image: ExternalBlob): Promise<void>;
    updateDailyLoginStreak(streak: bigint): Promise<void>;
    updateLastLoginTime(time: Time): Promise<void>;
    updatePowerUps(powerUps: bigint): Promise<void>;
}
import type { DailyMission as _DailyMission, ExternalBlob as _ExternalBlob, GameMode as _GameMode, MissionReward as _MissionReward, MissionType as _MissionType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyMissions(): Promise<Array<DailyMission> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyMissions();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyMissions();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDailyMissions(arg0: Array<DailyMission>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyMissions(to_candid_vec_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyMissions(to_candid_vec_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async selectGameMode(arg0: GameMode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.selectGameMode(to_candid_GameMode_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.selectGameMode(to_candid_GameMode_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAvatar(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvatar(await to_candid_ExternalBlob_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvatar(await to_candid_ExternalBlob_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDailyLoginStreak(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDailyLoginStreak(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDailyLoginStreak(arg0);
            return result;
        }
    }
    async updateLastLoginTime(arg0: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastLoginTime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastLoginTime(arg0);
            return result;
        }
    }
    async updatePowerUps(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePowerUps(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePowerUps(arg0);
            return result;
        }
    }
}
function from_candid_DailyMission_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyMission): DailyMission {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GameMode_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameMode): GameMode {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MissionReward_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MissionReward): MissionReward {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_MissionType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MissionType): MissionType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_DailyMission>]): Array<DailyMission> | null {
    return value.length === 0 ? null : from_candid_vec_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastLoginTime: _Time;
    powerUps: bigint;
    name: string;
    preferredGameMode: _GameMode;
    dailyLoginStreak: bigint;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    lastLoginTime: Time;
    powerUps: bigint;
    name: string;
    preferredGameMode: GameMode;
    dailyLoginStreak: bigint;
    avatar?: ExternalBlob;
}> {
    return {
        lastLoginTime: value.lastLoginTime,
        powerUps: value.powerUps,
        name: value.name,
        preferredGameMode: from_candid_GameMode_n13(_uploadFile, _downloadFile, value.preferredGameMode),
        dailyLoginStreak: value.dailyLoginStreak,
        avatar: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reward: _MissionReward;
    missionType: _MissionType;
    completed: boolean;
    description: string;
    claimed: boolean;
    progress: bigint;
}): {
    reward: MissionReward;
    missionType: MissionType;
    completed: boolean;
    description: string;
    claimed: boolean;
    progress: bigint;
} {
    return {
        reward: from_candid_MissionReward_n23(_uploadFile, _downloadFile, value.reward),
        missionType: from_candid_MissionType_n25(_uploadFile, _downloadFile, value.missionType),
        completed: value.completed,
        description: value.description,
        claimed: value.claimed,
        progress: value.progress
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endless: null;
} | {
    strategy: null;
} | {
    advancedStrategy: null;
} | {
    powerBoost: null;
} | {
    timeAttack: null;
}): GameMode {
    return "endless" in value ? GameMode.endless : "strategy" in value ? GameMode.strategy : "advancedStrategy" in value ? GameMode.advancedStrategy : "powerBoost" in value ? GameMode.powerBoost : "timeAttack" in value ? GameMode.timeAttack : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    powerUps: bigint;
} | {
    comboBoost: number;
} | {
    points: bigint;
}): {
    __kind__: "powerUps";
    powerUps: bigint;
} | {
    __kind__: "comboBoost";
    comboBoost: number;
} | {
    __kind__: "points";
    points: bigint;
} {
    return "powerUps" in value ? {
        __kind__: "powerUps",
        powerUps: value.powerUps
    } : "comboBoost" in value ? {
        __kind__: "comboBoost",
        comboBoost: value.comboBoost
    } : "points" in value ? {
        __kind__: "points",
        points: value.points
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clearTotalLines: bigint;
} | {
    clearLines: bigint;
} | {
    completeGames: bigint;
} | {
    usePowerUps: bigint;
} | {
    comboMultiplier: bigint;
} | {
    scorePoints: bigint;
} | {
    triggerChains: bigint;
}): {
    __kind__: "clearTotalLines";
    clearTotalLines: bigint;
} | {
    __kind__: "clearLines";
    clearLines: bigint;
} | {
    __kind__: "completeGames";
    completeGames: bigint;
} | {
    __kind__: "usePowerUps";
    usePowerUps: bigint;
} | {
    __kind__: "comboMultiplier";
    comboMultiplier: bigint;
} | {
    __kind__: "scorePoints";
    scorePoints: bigint;
} | {
    __kind__: "triggerChains";
    triggerChains: bigint;
} {
    return "clearTotalLines" in value ? {
        __kind__: "clearTotalLines",
        clearTotalLines: value.clearTotalLines
    } : "clearLines" in value ? {
        __kind__: "clearLines",
        clearLines: value.clearLines
    } : "completeGames" in value ? {
        __kind__: "completeGames",
        completeGames: value.completeGames
    } : "usePowerUps" in value ? {
        __kind__: "usePowerUps",
        usePowerUps: value.usePowerUps
    } : "comboMultiplier" in value ? {
        __kind__: "comboMultiplier",
        comboMultiplier: value.comboMultiplier
    } : "scorePoints" in value ? {
        __kind__: "scorePoints",
        scorePoints: value.scorePoints
    } : "triggerChains" in value ? {
        __kind__: "triggerChains",
        triggerChains: value.triggerChains
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyMission>): Array<DailyMission> {
    return value.map((x)=>from_candid_DailyMission_n21(_uploadFile, _downloadFile, x));
}
function to_candid_DailyMission_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyMission): _DailyMission {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GameMode_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_MissionReward_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MissionReward): _MissionReward {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_MissionType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MissionType): _MissionType {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastLoginTime: Time;
    powerUps: bigint;
    name: string;
    preferredGameMode: GameMode;
    dailyLoginStreak: bigint;
    avatar?: ExternalBlob;
}): Promise<{
    lastLoginTime: _Time;
    powerUps: bigint;
    name: string;
    preferredGameMode: _GameMode;
    dailyLoginStreak: bigint;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        lastLoginTime: value.lastLoginTime,
        powerUps: value.powerUps,
        name: value.name,
        preferredGameMode: to_candid_GameMode_n29(_uploadFile, _downloadFile, value.preferredGameMode),
        dailyLoginStreak: value.dailyLoginStreak,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n31(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reward: MissionReward;
    missionType: MissionType;
    completed: boolean;
    description: string;
    claimed: boolean;
    progress: bigint;
}): {
    reward: _MissionReward;
    missionType: _MissionType;
    completed: boolean;
    description: string;
    claimed: boolean;
    progress: bigint;
} {
    return {
        reward: to_candid_MissionReward_n35(_uploadFile, _downloadFile, value.reward),
        missionType: to_candid_MissionType_n37(_uploadFile, _downloadFile, value.missionType),
        completed: value.completed,
        description: value.description,
        claimed: value.claimed,
        progress: value.progress
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): {
    endless: null;
} | {
    strategy: null;
} | {
    advancedStrategy: null;
} | {
    powerBoost: null;
} | {
    timeAttack: null;
} {
    return value == GameMode.endless ? {
        endless: null
    } : value == GameMode.strategy ? {
        strategy: null
    } : value == GameMode.advancedStrategy ? {
        advancedStrategy: null
    } : value == GameMode.powerBoost ? {
        powerBoost: null
    } : value == GameMode.timeAttack ? {
        timeAttack: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "powerUps";
    powerUps: bigint;
} | {
    __kind__: "comboBoost";
    comboBoost: number;
} | {
    __kind__: "points";
    points: bigint;
}): {
    powerUps: bigint;
} | {
    comboBoost: number;
} | {
    points: bigint;
} {
    return value.__kind__ === "powerUps" ? {
        powerUps: value.powerUps
    } : value.__kind__ === "comboBoost" ? {
        comboBoost: value.comboBoost
    } : value.__kind__ === "points" ? {
        points: value.points
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "clearTotalLines";
    clearTotalLines: bigint;
} | {
    __kind__: "clearLines";
    clearLines: bigint;
} | {
    __kind__: "completeGames";
    completeGames: bigint;
} | {
    __kind__: "usePowerUps";
    usePowerUps: bigint;
} | {
    __kind__: "comboMultiplier";
    comboMultiplier: bigint;
} | {
    __kind__: "scorePoints";
    scorePoints: bigint;
} | {
    __kind__: "triggerChains";
    triggerChains: bigint;
}): {
    clearTotalLines: bigint;
} | {
    clearLines: bigint;
} | {
    completeGames: bigint;
} | {
    usePowerUps: bigint;
} | {
    comboMultiplier: bigint;
} | {
    scorePoints: bigint;
} | {
    triggerChains: bigint;
} {
    return value.__kind__ === "clearTotalLines" ? {
        clearTotalLines: value.clearTotalLines
    } : value.__kind__ === "clearLines" ? {
        clearLines: value.clearLines
    } : value.__kind__ === "completeGames" ? {
        completeGames: value.completeGames
    } : value.__kind__ === "usePowerUps" ? {
        usePowerUps: value.usePowerUps
    } : value.__kind__ === "comboMultiplier" ? {
        comboMultiplier: value.comboMultiplier
    } : value.__kind__ === "scorePoints" ? {
        scorePoints: value.scorePoints
    } : value.__kind__ === "triggerChains" ? {
        triggerChains: value.triggerChains
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DailyMission>): Array<_DailyMission> {
    return value.map((x)=>to_candid_DailyMission_n33(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
