/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyMission {
  'reward' : MissionReward,
  'missionType' : MissionType,
  'completed' : boolean,
  'description' : string,
  'claimed' : boolean,
  'progress' : bigint,
}
export type ExternalBlob = Uint8Array;
export type GameMode = { 'endless' : null } |
  { 'strategy' : null } |
  { 'advancedStrategy' : null } |
  { 'powerBoost' : null } |
  { 'timeAttack' : null };
export type MissionReward = { 'powerUps' : bigint } |
  { 'comboBoost' : number } |
  { 'points' : bigint };
export type MissionType = { 'clearTotalLines' : bigint } |
  { 'clearLines' : bigint } |
  { 'completeGames' : bigint } |
  { 'usePowerUps' : bigint } |
  { 'comboMultiplier' : bigint } |
  { 'scorePoints' : bigint } |
  { 'triggerChains' : bigint };
export type Time = bigint;
export interface UserProfile {
  'lastLoginTime' : Time,
  'powerUps' : bigint,
  'name' : string,
  'preferredGameMode' : GameMode,
  'dailyLoginStreak' : bigint,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyMissions' : ActorMethod<[], [] | [Array<DailyMission>]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDailyMissions' : ActorMethod<[Array<DailyMission>], undefined>,
  'selectGameMode' : ActorMethod<[GameMode], undefined>,
  'updateAvatar' : ActorMethod<[ExternalBlob], undefined>,
  'updateDailyLoginStreak' : ActorMethod<[bigint], undefined>,
  'updateLastLoginTime' : ActorMethod<[Time], undefined>,
  'updatePowerUps' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];